apps/panels/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *
from . import views

app_name = 'panels' 


urlpatterns = [
    path('', views.panels, name='panel'),

    path('society/<int:society_id>/poll/create/', views.create_poll, name='create_poll'),
    path('society/<int:society_id>/polls/', views.poll_list, name='poll_list'),
    path('society/<int:society_id>/poll/<int:poll_id>/question/add/', views.add_question, name='add_question'),
    path('society/<int:society_id>/poll/<int:poll_id>/question/<int:question_id>/vote/', views.vote, name='vote'),
    path('society/<int:society_id>/poll/<int:poll_id>/question/<int:question_id>/result/', views.poll_result, name='poll_result'),
    path('society/<int:society_id>/poll/<int:poll_id>/question/<int:question_id>/cancel/', views.cancel_vote, name='cancel_vote'),
    
    path('society/<int:society_id>/galleries/', views.society_gallery_list, name='society_gallery_list'),
    path('society/<int:society_id>/gallery/create/', views.create_gallery, name='create_gallery'),
    path('society/<int:society_id>/gallery/<int:gallery_id>/', views.gallery_detail, name='gallery_detail'),
    path('society/<int:society_id>/gallery/<int:gallery_id>/upload/', views.upload_image, name='upload_image'),
    path('society/<int:society_id>/image/<int:image_id>/delete/', views.delete_image, name='delete_image'),

    path('society/<int:society_id>/comments/', views.society_comment_feed, name='society_comment_feed'),
    path('comment/<int:society_id>/comments/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
    path('comment/<int:society_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('comment/<int:society_id>/comments/<int:comment_id>/like/', views.toggle_like_comment, name='like_comment'),

    path('society/<int:society_id>/match/record/', views.record_match, name='record_match'),
    path('society/<int:society_id>/ranking/', views.society_ranking, name='society_ranking'),
    path('society/<int:society_id>/hall-of-fame/', views.hall_of_fame, name='hall_of_fame'),
    path('society/<int:society_id>/hall-of-fame/update/', views.update_hall_of_fame_view, name='update_hall_of_fame'),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home
from pathlib import Path
from .views import ai_search
from apps.events.views import event_list
BASE_DIR = Path(__file__).resolve().parent.parent  # ✅ Define BASE_DIR

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('events/', include('apps.events.urls')),
    path('news/', include('apps.news.urls')),
    path('societies/', include('apps.societies.urls')),
    path('panels/', include('apps.panels.urls')),
    path('users/', include('apps.users.urls')),
    path('search/', ai_search, name='ai_search'),
    path('payments/', include('apps.payments.urls')),
    path('api/events/', event_list, name='event_list'),
    path('widgets/', include('apps.widgets.urls') )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=BASE_DIR / "config/static")

apps/panels/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Comment, Poll, Gallery, Image, Question, Option

#comments
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        # widgets = {
        #     'content': forms.Textarea(attrs={ 'class': 'form-control', 'rows': 3, 'placeholder': 'Make a comment...'}),
        # }
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

#gallery
class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image']

#poll
class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['title', 'description', 'deadline']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']

class OptionForm(forms.ModelForm):
    class Meta:
        model = Option
        fields = ('option_text',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['option_text'].required = True

    def clean_option_text(self):
        data = self.cleaned_data.get('option_text', "").strip()
        if not data:
            raise forms.ValidationError("This field is required.")
        return data

OptionFormSet = forms.modelformset_factory(
    Option,
    form=OptionForm,  
    fields=('option_text',),
    extra=1,
    min_num=1,
    validate_min=True,
    can_delete=False
)

apps/panels/views.py
from django.contrib.auth.decorators import login_required
from .models import Question, Option, Vote, Poll, Comment, Gallery, Image
import os
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from apps.societies.models import Society
from .forms import *
from django.http import HttpResponseForbidden
from django.utils.timezone import now
from apps.panels.models import Match, MemberRating, HallOfFame
from apps.societies.models import Society, Membership, MembershipRole
from django.contrib.auth import get_user_model



def panels(request):
    return render(request, 'panels.html')

@login_required
def create_poll(request, society_id):
    society = get_object_or_404(Society, id=society_id)

    if request.method == 'POST':
        form = PollForm(request.POST)
        if form.is_valid():
            poll = form.save(commit=False)
            poll.society = society
            poll.save()
            return redirect('panels:add_question', society_id=society.id, poll_id=poll.id)
    else:
        form = PollForm()

    return render(request, 'create_poll.html', {'form': form, 'society': society})

@login_required
def add_question(request, society_id, poll_id):
    society = get_object_or_404(Society, id=society_id)
    poll = get_object_or_404(Poll, id=poll_id, society=society)

    extra_forms = int(request.GET.get('extra', 3))  # default to 3 options

    OptionFormSetCustom = modelformset_factory(
        Option,
        fields=('option_text',),
        extra=extra_forms,
        can_delete=False
    )

    if request.method == 'POST':
        q_form = QuestionForm(request.POST)
        o_formset = OptionFormSetCustom(request.POST)

        if q_form.is_valid() and o_formset.is_valid():
            question = q_form.save(commit=False)
            question.poll = poll
            question.save()

            for form in o_formset:
                option = form.save(commit=False)
                option.question = question
                option.save()

            return redirect('panels:poll_list', society_id=society.id)
    else:
        q_form = QuestionForm()
        o_formset = OptionFormSetCustom(queryset=Option.objects.none())

    return render(request, 'add_question.html', {
        'poll': poll,
        'society': society,
        'q_form': q_form,
        'o_formset': o_formset,
        'extra_forms': extra_forms,
    })


@login_required
def poll_list(request, society_id):
    society = get_object_or_404(Society, id=society_id)
    polls = Poll.objects.filter(society=society)
    return render(request, 'poll_list.html', {'polls': polls, 'society': society})


@login_required
def vote(request, society_id, poll_id, question_id):
    society = get_object_or_404(Society, id=society_id)
    poll = get_object_or_404(Poll, id=poll_id, society=society)
    question = get_object_or_404(Question, id=question_id, poll=poll)

    if poll.is_closed():
        return render(request, 'poll_closed.html', {'poll': poll})

    options = question.options.all()
    user_vote = Vote.objects.filter(voted_by=request.user, option__question=question).first()
    user_selected_option = user_vote.option if user_vote else None

    if request.method == 'POST' and not user_vote:
        selected_option_id = request.POST.get('option')
        if selected_option_id:
            selected_option = get_object_or_404(Option, id=selected_option_id, question=question)
            Vote.objects.create(option=selected_option, voted_by=request.user)
            selected_option.option_count += 1
            selected_option.save()
            return redirect('panels:poll_result', society_id=society.id, poll_id=poll.id, question_id=question.id)

    return render(request, 'vote.html', {
        'society': society,
        'poll': poll,
        'question': question,
        'options': options,
        'user_selected_option': user_selected_option
    })

@login_required
def poll_result(request, society_id, poll_id, question_id):
    society = get_object_or_404(Society, id=society_id)
    poll = get_object_or_404(Poll, id=poll_id, society=society)
    question = get_object_or_404(Question, id=question_id, poll=poll)
    options = question.options.all()
    total_votes = sum([opt.option_count for opt in options])

    return render(request, 'poll_result.html', {
        'society': society,
        'poll': poll,
        'question': question,
        'options': options,
        'total_votes': total_votes
    })

@login_required
def cancel_vote(request, society_id, poll_id, question_id):
    society = get_object_or_404(Society, id=society_id)
    poll = get_object_or_404(Poll, id=poll_id, society=society)
    question = get_object_or_404(Question, id=question_id, poll=poll)

    vote = Vote.objects.filter(voted_by=request.user, option__question=question).first()

    if vote:
        selected_option = vote.option
        vote.delete()
        selected_option.option_count = max(selected_option.option_count - 1, 0)
        selected_option.save()

    return redirect('panels:vote', society_id=society.id, poll_id=poll.id, question_id=question.id)


#gallery
@login_required
def society_gallery_list(request, society_id):
    society = get_object_or_404(Society, id=society_id)
    galleries = Gallery.objects.filter(society=society)
    return render(request, 'society_gallery_list.html', {
        'society': society,
        'galleries': galleries,
    })


@login_required
def create_gallery(request, society_id):
    society = get_object_or_404(Society, id=society_id)

    if request.method == 'POST':
        form = GalleryForm(request.POST)
        if form.is_valid():
            gallery = form.save(commit=False)
            gallery.society = society
            gallery.save()
            return redirect('panels:gallery_detail', society_id=society.id, gallery_id=gallery.id)
    else:
        form = GalleryForm()

    return render(request, 'create_gallery.html', {'form': form, 'society': society})


@login_required
def gallery_detail(request, society_id, gallery_id):
    society = get_object_or_404(Society, id=society_id)
    gallery = get_object_or_404(Gallery, id=gallery_id, society=society)
    images = gallery.images.all()
    return render(request, 'gallery_detail.html', {
        'society': society,
        'gallery': gallery,
        'images': images
    })


@login_required
def upload_image(request, society_id, gallery_id):
    society = get_object_or_404(Society, id=society_id)
    gallery = get_object_or_404(Gallery, id=gallery_id, society=society)

    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.gallery = gallery
            image.uploaded_by = request.user
            image.save()
            return redirect('panels:gallery_detail', society_id=society.id, gallery_id=gallery.id)
    else:
        form = ImageUploadForm()

    return render(request, 'upload_image.html', {
        'form': form,
        'gallery': gallery,
        'society': society
    })


@login_required
def delete_image(request, society_id, image_id):
    society = get_object_or_404(Society, id=society_id)
    image = get_object_or_404(Image, id=image_id)
    gallery = image.gallery

    if gallery.society.id != society.id:
        return HttpResponseForbidden("You can't delete this image.")

    if request.method == 'POST':
        image.delete()
        return redirect('panels:gallery_detail', society_id=society.id, gallery_id=gallery.id)

    return render(request, 'confirm_delete.html', {
        'image': image,
        'society': society
    })

#comment
@login_required
def society_comment_feed(request, society_id):
    society = get_object_or_404(Society, id=society_id)
    comments = society.comments.all().order_by('-created_at')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.society = society
            comment.author = request.user
            comment.save()
            return redirect('panels:society_comment_feed', society_id=society.id)
    else:
        form = CommentForm()

    return render(request, 'society_comment_feed.html', {
        'society': society,
        'comments': comments,
        'form': form
    })

@login_required
def edit_comment(request, society_id, comment_id):
    society = get_object_or_404(Society, id=society_id)
    comment = get_object_or_404(Comment, id=comment_id, society=society)

    if comment.author != request.user:
        messages.error(request, "You don't have permission to edit this comment.")
        return redirect('panels:society_comment_feed', society_id=society.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('panels:society_comment_feed', society_id=society.id)
    else:
        form = CommentForm(instance=comment)

    return render(request, 'edit_comment.html', {
        'form': form,
        'comment': comment,
        'society': society,
    })


@login_required
def delete_comment(request, society_id, comment_id):
    society = get_object_or_404(Society, id=society_id)
    comment = get_object_or_404(Comment, id=comment_id, society=society)

    if comment.author != request.user:
        messages.error(request, "You don't have permission to delete this comment.")
        return redirect('panels:society_comment_feed', society_id=society.id)

    if request.method == 'POST':
        comment.delete()
        return redirect('panels:society_comment_feed', society_id=society.id)

    return render(request, 'confirm_delete_comment.html', {
        'comment': comment,
        'society': society
    })


@login_required
def toggle_like_comment(request, society_id, comment_id):

apps/panels/templates/add_question.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-4">



<form method="post">
    <h3>Question</h3>
    {% csrf_token %}
    {{ q_form.as_p }}

    <h3 class="mt-4">Options</h3>
    {{ o_formset.management_form }}
    {% for form in o_formset %}
      {{ form.as_p }}
    {% endfor %}

    <button type="submit" class="btn btn-primary mt-3">Save Question</button>
  </form>

  <a class="btn btn-link mt-3" href="?extra={{ extra_forms|add:'1' }}">+ Add another option</a><br>
  <a class="btn btn-secondary mt-2" href="{% url 'panels:poll_list' society.id %}">← Back to Poll List</a>
</div>

{% endblock %}

apps/panels/templates/confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <h2 class="my-4 text-center text-danger">Confirm Image Deletion</h2>
{% endblock %}

{% block content %}
<div class="container" style="max-width: 600px;">
  <div class="card shadow-sm p-4">
    <p>Are you sure you want to delete this image?</p>

    <img src="{{ image.image.url }}" alt="Image" class="img-fluid mb-3" style="max-height: 300px; border-radius: 6px;">

    <form method="post" class="d-inline">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Yes, delete</button>
    </form>
    <a href="{% url 'panels:gallery_detail' society.id image.gallery.id %}" class="btn btn-secondary ms-2">Cancel</a>
  </div>
</div>
{% endblock %}

apps/panels/templates/confirm_delete_comment.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Confirm Delete - Comment
{% endblock %}

{% block content %}
<div class="container mt-5 px-4 px-md-5" style="max-width: 700px;">
  <div class="card shadow-sm">
    <div class="card-header bg-danger text-white">
      <h5 class="mb-0">Confirm Delete</h5>
    </div>
    <div class="card-body">
      <p class="mb-3">Are you sure you want to delete this comment?</p>

      <blockquote class="blockquote px-3">
        <p class="mb-2 fs-5">{{ comment.content }}</p>
        <footer class="blockquote-footer mt-2">By: {{ comment.author }}</footer>
      </blockquote>

      <form method="post" class="mt-4 d-flex gap-3">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="{% url 'panels:society_comment_feed' society.id %}" class="btn btn-secondary">Cancel</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

apps/panels/templates/create_gallery.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<div class="bg-light p-4 rounded shadow-sm mb-4">
  <h2 class="mb-1">Create a New Gallery</h2>
  <p class="text-muted">for {{ society.name }}</p>
</div>
{% endblock %}

{% block content %}
<h2 class="mb-1">Create a New Gallery</h2>
<p class="text-muted">for {{ society.name }}</p>
<div class="card p-4 mb-4">
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      {{ form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">Create Gallery</button>
  </form>
</div>

<a href="{% url 'panels:society_gallery_list' society.id %}" class="btn btn-outline-secondary mt-2">← Back to Gallery List</a>
{% endblock %}

apps/panels/templates/create_poll.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="mb-4">Create Poll for {{ society.name }}</h2>

      <form method="post" class="mb-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create Poll</button>
      </form>

      <a href="{% url 'panels:poll_list' society.id %}" class="btn btn-secondary mt-4 mb-5">← Back to Poll List</a>
    </div>
  </div>
</div>
{% endblock %}

apps/panels/templates/edit_comment.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
<h2 class="my-4 text-center">Edit Comment</h2>
{% endblock %}

{% block content %}
<div class="container" style="max-width: 600px;">
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      {{ form.content.label_tag }}
      {{ form.content|add_class:"form-control" }}
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
    <a href="{% url 'panels:society_comment_feed' society.id %}" class="btn btn-secondary ms-2">Cancel</a>
  </form>
</div>
{% endblock %}

apps/panels/templates/hall_of_fame.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ society.name }} - Hall of Fame 🏆</h2>

<a href="{% url 'panels:update_hall_of_fame' society.id %}" class="btn btn-primary">🔄 Update</a>
<a href="{% url 'panels:society_ranking' society.id %}" class="btn btn-outline-secondary">📊 Rankings</a>

<table>
  <thead>
    <tr>
      <th>Season</th>
      <th>Top Member</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    {% for hof in hof_entries %}
      <tr>
        <td>{{ hof.season }}</td>
        <td>{{ hof.member.preferred_name }}</td>
        <td>{{ hof.highest_rating }}</td>
      </tr>
    {% empty %}
      <tr><td colspan="3">No data yet.</td></tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

apps/panels/templates/panels.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dynamic Society Panel</title>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
  <h1>Welcome to the Test Page</h1>
  <p>This is a simple test page rendered by Django views.</p>

  <h2>📊 Polls</h2>
  <div id="poll"></div>

  <h2>🖼 Gallery</h2>
  <div id="gallery"></div>

  <h2>💬 Comments</h2>
  <div id="comments"></div>

  <script>
    const societyId = 1; 

    $(document).ready(function () {
      $('#poll').load(`/panels/society/${societyId}/polls/`, function(response, status, xhr) {
        if (status === "error") {
          $('#poll').html("<p>Error loading polls.</p>");
        }
      });

      $('#gallery').load(`/panels/society/${societyId}/galleries/`, function(response, status, xhr) {
        if (status === "error") {
          $('#gallery').html("<p>Error loading galleries.</p>");
        }
      });

      $('#comments').load(`/panels/society/${societyId}/comments/`, function(response, status, xhr) {
        if (status === "error") {
          $('#comments').html("<p>Error loading comments.</p>");
        }
      });
    });
  </script>
</body>
</html>

apps/panels/templates/ranking.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ society.name }} - Rankings 📊</h2>

<a href="{% url 'panels:record_match' society.id %}" class="btn btn-primary">➕ Record Match</a>
<a href="{% url 'panels:hall_of_fame' society.id %}" class="btn btn-outline-secondary">🏆 Hall of Fame</a>

<ol>
  {% for r in rankings %}
    <li>{{ r.member.preferred_name }} — {{ r.rating }} pts</li>
  {% endfor %}
</ol>
{% endblock %}

apps/panels/templates/record_match.html
{% extends 'base.html' %}
{% block content %}
<h2>Record a Match - {{ society.name }}</h2>

<form method="post">
  {% csrf_token %}
  <label>Player 1:</label>
  <select name="player1">
    {% for m in members %}
      <option value="{{ m.id }}">{{ m.preferred_name }}</option>
    {% endfor %}
  </select><br><br>

  <label>Player 2:</label>
  <select name="player2">
    {% for m in members %}
      <option value="{{ m.id }}">{{ m.preferred_name }}</option>
    {% endfor %}
  </select><br><br>

  <label>Winner:</label>
  <select name="winner">
    <option value="">Draw</option>
    {% for m in members %}
      <option value="{{ m.id }}">{{ m.preferred_name }}</option>
    {% endfor %}
  </select><br><br>

  <label>Player 1 Delta:</label>
  <input type="number" name="player1_delta"><br><br>

  <label>Player 2 Delta:</label>
  <input type="number" name="player2_delta"><br><br>

  <label>Notes:</label><br>
  <textarea name="notes" rows="3" cols="50"></textarea><br><br>

  <button type="submit">Save Match</button>
</form>
{% endblock %}

apps/panels/templates/society_comment_feed.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
<h2 class="my-4 text-center">Comments for {{ society.name }}</h2>
{% endblock %}

{% block content %}
<div class="container" style="max-width: 800px;">
  <form method="post" class="mb-4">
    {% csrf_token %}
    <div class="mb-3">
      {{ form.content.label_tag }}
      {{ form.content|add_class:"form-control" }}
    </div>
    <button type="submit" class="btn btn-primary">Post Comment</button>
  </form>

  <hr>

  {% if comments %}
    <div class="list-group">
      {% for comment in comments %}
        <div class="list-group-item mb-3">
          <p class="mb-1"><strong>{{ comment.author }}</strong> <span class="text-muted small">on {{ comment.created_at|date:"Y-m-d H:i" }}</span></p>
          <p>{{ comment.content }}</p>

          <div class="d-flex justify-content-between align-items-center">
            <div>
              <a href="{% url 'panels:like_comment' society.id comment.id %}" class="btn btn-sm btn-outline-danger">
                {% if user in comment.likes.all %} ❤️ Unlike {% else %} 🤍 Like {% endif %} ({{ comment.likes.count }})
              </a>
            </div>
            {% if comment.author == user %}
              <div>
                <a href="{% url 'panels:edit_comment' society.id comment.id %}" class="btn btn-sm btn-secondary">✏️ Edit</a>
                <a href="{% url 'panels:delete_comment' society.id comment.id %}" class="btn btn-sm btn-danger">🗑 Delete</a>
              </div>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p class="text-muted">No comments yet. Be the first!</p>
  {% endif %}
  <a class="btn btn-primary" href="{% url 'society_page' society.id %}">Back</a>
</div>
{% endblock %}

apps/panels/templates/society_gallery_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <h2 class="my-4 text-center">Galleries</h2>
{% endblock %}

{% block content %}
<div class="container" style="max-width: 700px;">
  <div class="card shadow-sm p-4 mb-4">
    <h2>{{ society.name }} Galleries</h2>
    <ul class="list-group list-group-flush">
      {% for gallery in galleries %}
        <li class="list-group-item">
          <a href="{% url 'panels:gallery_detail' society.id gallery.id %}">
            {{ gallery.title }}
          </a>
        </li>
      {% empty %}
        <li class="list-group-item text-muted">No galleries yet.</li>
      {% endfor %}
    </ul>
  {% if user_membership and user_membership.role == "manager" or user_membership and user_membership.role == "co_manager" or user_membership and user_membership.role == "editor" or user.is_superuser %}    <div class="mt-3 text-end">
          <a href="{% url 'panels:create_gallery' society.id %}" class="btn btn-primary">+ Create New Gallery</a>
    </div>
  </div>
</div>
  {% endif %}
  <a class="btn btn-outline-secondary" href="{% url 'society_page' society.id %}"> ← Back</a>
{% endblock %}

apps/panels/templates/upload_image.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<div class="bg-light p-4 rounded shadow-sm mb-4">
  <h2 class="mb-1">Upload an Image to "{{ gallery.title }}"</h2>
</div>
{% endblock %}

{% block content %}
<h3 class="mb-1">Upload an Image to "{{ gallery.title }}"</h3>
<div class="card shadow-sm p-4">
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      {{ form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
</div>

<a href="{% url 'panels:gallery_detail' society.id gallery.id %}" class="btn btn-outline-secondary mt-2">← Back to Gallery</a>
{% endblock %}

apps/panels/templates/vote.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <h2 class="my-4 text-center">{{ question.question_text }}</h2>
{% endblock %}

{% block content %}
<div class="container" style="max-width: 800px;">
  <div class="card mb-4 shadow-sm">
    <h3 class="my-4 text-center">{{ question.question_text }}</h3>
    <div class="card-body">
      {% if user_selected_option %}
        <p class="mb-3">
          ✅ You have already voted for: 
          <strong>{{ user_selected_option.option_text }}</strong>
        </p>
        <a href="{% url 'panels:cancel_vote' society.id poll.id question.id %}" class="btn btn-outline-danger mb-3">
          ❌ Cancel Vote
        </a>
      {% else %}
        <form method="post">
          {% csrf_token %}
          <div class="mb-3">
            {% for option in options %}
              <div class="form-check mb-2">
                <input class="form-check-input" type="radio" name="option" value="{{ option.id }}" id="option{{ option.id }}">
                <label class="form-check-label" for="option{{ option.id }}">
                  {{ option.option_text }}
                </label>
              </div>
            {% endfor %}
          </div>
          <button type="submit" class="btn btn-primary">Submit Vote</button>
        </form>
      {% endif %}
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <a href="{% url 'panels:poll_result' society.id poll.id question.id %}" class="btn btn-outline-secondary">
      📊 View Results
    </a>
    <a href="{% url 'panels:poll_list' society.id %}" class="btn btn-outline-secondary">
      ← Back to Poll List
    </a>
  </div>
</div>
{% endblock %}